import pfam.PFAM;

public class PFAMTest {

	public static void main(String[] args) {
		PFAM pfam = new PFAM();
		pfam.request(">Hello World", "MMKRQLHRMRQLAQTGSLGRTPETAEFLGEDLLQVEQRLEPAKRAAHNIHKRLQACLQGQ" + 
				"SGADMDKRVKKLPLMALSTTMAESFKELDPDSSMGKALEMSCAIQNQLARILAEFEMTLE" + 
				"RDVLQPLSRLSEEELPAILKHKKSLQKLVSDWNTLKSRLSQATKNSGSSQGLGGSPGSHS" + 
				"HTTMANKVETLKEEEEELKRKVEQCRDEYLADLYHFVTKEDSYANYFIRLLEIQADYHRR" + 
				"SLSSLDTALAELRENHGQADHSPSMTATHFPRVYGVSLATHLQELGREIALPIEACVMML" + 
				"LSEGMKEEGLFRLAAGASVLKRLKQTMASDPHSLEEFCSDPHAVAGALKSYLRELPEPLM" + 
				"TFDLYDDWMRAASLKEPGARLQALQEVCSRLPPENLSNLRYLMKFLARLAEEQEVNKMTP" + 
				"SNIAIVLGPNLLWPPEKEGDQAQLDAASVSSIQVVGVVEALIQSADTLFPGDINFNVSGL" + 
				"FSAVTLQDTVSDRLASEELPSTAVPTPATTPAPAPAPAPAPAPALASAATKERTESEVPP" + 
				"RPASPKVTRSPPETAAPVEDMARRTKRPAPARPTMPPPQVSGSRSSPPAPPLPPGSGSPG" + 
				"TPQALPRRLVGSSLRAPTVPPPLPPTPPQPARRQSRRSPASPSPASPGPASPSPVSLSNP" + 
				"AQVDLGAATAEGGAPEAISGVPTPPAIPPQPRPRSLASETN");
	}
}
